# Generated by Django 4.0.4 on 2022-06-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.CharField(max_length=255, null=True, verbose_name='Сервис активации'),
        ),
        migrations.AddField(
            model_name='product',
            name='oc',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='pros',
            field=models.CharField(max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=255, null=True, verbose_name='Оперативка'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(max_length=255, null=True, verbose_name='Место на диске'),
        ),
        migrations.AddField(
            model_name='product',
            name='vidyha',
            field=models.CharField(max_length=255, null=True, verbose_name='Видеокарта'),
        ),
        migrations.CreateModel(
            name='ProductShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='The title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Image')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Product shot',
                'verbose_name_plural': 'Product shots',
            },
        ),
    ]
