# Generated by Django 4.0.4 on 2022-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_activate_product_oc_product_pros_product_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oc',
            field=models.CharField(max_length=255, null=True, verbose_name='Операционная система'),
        ),
    ]
